
 const Ingredientes = [
    {"drinks":[
        {"idIngredient":"0","strIngredient1":"Light rum"},
        {"idIngredient":"1","strIngredient1":"Applejack"},
        {"idIngredient":"2","strIngredient1":"Gin"},
        {"idIngredient":"3","strIngredient1":"Dark rum"},
        {"idIngredient":"4","strIngredient1":"Sweet Vermouth"},
        {"idIngredient":"5","strIngredient1":"Strawberry schnapps"},
        {"idIngredient":"6","strIngredient1":"Scotch"},
        {"idIngredient":"7","strIngredient1":"Apricot brandy"},
        {"idIngredient":"8","strIngredient1":"Triple sec"},
        {"idIngredient":"9","strIngredient1":"Southern Comfort"},
        {"idIngredient":"10","strIngredient1":"Orange bitters"},
        {"idIngredient":"11","strIngredient1":"Brandy"},
        {"idIngredient":"12","strIngredient1":"Lemon vodka"},
        {"idIngredient":"13","strIngredient1":"Blended whiskey"},
        {"idIngredient":"14","strIngredient1":"Dry Vermouth"},
        {"idIngredient":"15","strIngredient1":"Amaretto"},
        {"idIngredient":"16","strIngredient1":"Tea"},
        {"idIngredient":"17","strIngredient1":"Champagne"},
        {"idIngredient":"18","strIngredient1":"Coffee liqueur"},
        {"idIngredient":"19","strIngredient1":"Bourbon"},
        {"idIngredient":"20","strIngredient1":"Tequila"},
        {"idIngredient":"21","strIngredient1":"Vodka"},
        {"idIngredient":"22","strIngredient1":"A\u00f1ejo rum"},
        {"idIngredient":"23","strIngredient1":"Bitters"},
        {"idIngredient":"24","strIngredient1":"Sugar"},
        {"idIngredient":"25","strIngredient1":"Kahlua"},
        {"idIngredient":"26","strIngredient1":"Demerara Sugar"},
        {"idIngredient":"27","strIngredient1":"Dubonnet Rouge"},
        {"idIngredient":"28","strIngredient1":"Watermelon"},
        {"idIngredient":"29","strIngredient1":"Lime juice"},
        {"idIngredient":"30","strIngredient1":"Irish whiskey"},
        {"idIngredient":"31","strIngredient1":"Apple brandy"},
        {"idIngredient":"32","strIngredient1":"Carbonated water"},
        {"idIngredient":"33","strIngredient1":"Cherry brandy"},
        {"idIngredient":"34","strIngredient1":"Creme de Cacao"},
        {"idIngredient":"35","strIngredient1":"Grenadine"},
        {"idIngredient":"36","strIngredient1":"Port"},
        {"idIngredient":"37","strIngredient1":"Coffee brandy"},
        {"idIngredient":"38","strIngredient1":"Red wine"},
        {"idIngredient":"39","strIngredient1":"Rum"},
        {"idIngredient":"40","strIngredient1":"Grapefruit juice"},
        {"idIngredient":"41","strIngredient1":"Ricard"},
        {"idIngredient":"42","strIngredient1":"Sherry"},
        {"idIngredient":"43","strIngredient1":"Cognac"},
        {"idIngredient":"44","strIngredient1":"Sloe gin"},
        {"idIngredient":"45","strIngredient1":"Apple juice"},
        {"idIngredient":"46","strIngredient1":"Pineapple juice"},
        {"idIngredient":"47","strIngredient1":"Lemon juice"},
        {"idIngredient":"48","strIngredient1":"Sugar syrup"},
        {"idIngredient":"49","strIngredient1":"Milk"},
        {"idIngredient":"50","strIngredient1":"Strawberries"},
        {"idIngredient":"51","strIngredient1":"Chocolate syrup"},
        {"idIngredient":"52","strIngredient1":"Yoghurt"},
        {"idIngredient":"53","strIngredient1":"Mango"},
        {"idIngredient":"54","strIngredient1":"Ginger"},
        {"idIngredient":"55","strIngredient1":"Lime"},
        {"idIngredient":"56","strIngredient1":"Cantaloupe"},
        {"idIngredient":"57","strIngredient1":"Berries"},
        {"idIngredient":"58","strIngredient1":"Grapes"},
        {"idIngredient":"59","strIngredient1":"Kiwi"},
        {"idIngredient":"60","strIngredient1":"Tomato juice"},
        {"idIngredient":"61","strIngredient1":"Cocoa powder"},
        {"idIngredient":"62","strIngredient1":"Chocolate"},
        {"idIngredient":"63","strIngredient1":"Heavy cream"},
        {"idIngredient":"64","strIngredient1":"Galliano"},
        {"idIngredient":"65","strIngredient1":"Peach Vodka"},
        {"idIngredient":"66","strIngredient1":"Ouzo"},
        {"idIngredient":"67","strIngredient1":"Coffee"},
        {"idIngredient":"68","strIngredient1":"Spiced rum"},
        {"idIngredient":"69","strIngredient1":"Water"},
        {"idIngredient":"70","strIngredient1":"Espresso"},
        {"idIngredient":"71","strIngredient1":"Angelica root"},
        {"idIngredient":"72","strIngredient1":"Orange"},
        {"idIngredient":"73","strIngredient1":"Cranberries"},
        {"idIngredient":"74","strIngredient1":"Johnnie Walker"},
        {"idIngredient":"75","strIngredient1":"Apple cider"},
        {"idIngredient":"76","strIngredient1":"Everclear"},
        {"idIngredient":"77","strIngredient1":"Cranberry juice"},
        {"idIngredient":"78","strIngredient1":"Egg yolk"},
        {"idIngredient":"79","strIngredient1":"Egg"},
        {"idIngredient":"80","strIngredient1":"Grape juice"},
        {"idIngredient":"81","strIngredient1":"Peach nectar"},
        {"idIngredient":"82","strIngredient1":"Lemon"},
        {"idIngredient":"83","strIngredient1":"Firewater"},
        {"idIngredient":"84","strIngredient1":"Lemonade"},
        {"idIngredient":"85","strIngredient1":"Lager"},
        {"idIngredient":"86","strIngredient1":"Whiskey"},
        {"idIngredient":"87","strIngredient1":"Absolut Citron"},
        {"idIngredient":"88","strIngredient1":"Pisco"},
        {"idIngredient":"89","strIngredient1":"Irish cream"},
        {"idIngredient":"90","strIngredient1":"Ale"},
        {"idIngredient":"91","strIngredient1":"Chocolate liqueur"},
        {"idIngredient":"92","strIngredient1":"Midori melon liqueur"},
        {"idIngredient":"93","strIngredient1":"Sambuca"},
        {"idIngredient":"94","strIngredient1":"Cider"},
        {"idIngredient":"95","strIngredient1":"Sprite"},
        {"idIngredient":"96","strIngredient1":"7-Up"},
        {"idIngredient":"97","strIngredient1":"Blackberry brandy"},
        {"idIngredient":"98","strIngredient1":"Peppermint schnapps"}
        
    ]}
    ]

export default Ingredientes;